# Generated by Django 3.1.7 on 2021-04-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210405_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='slug',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
