# Generated by Django 3.1.7 on 2021-04-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210405_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
